// 中文输入法合成期间不重绘输入框；确认输入后再刷新结果。
let searchComposing=false,searchTimer=null;
function applySearch(input){if(!input||input.id!=='search')return;search=input.value;const position=input.selectionStart;page=1;const content=document.querySelector('#content');if(!content)return;content.innerHTML=renderView();const replacement=document.querySelector('#search');if(replacement){replacement.focus();replacement.setSelectionRange(position,position)}}
document.addEventListener('compositionstart',e=>{if(e.target.id==='search'){searchComposing=true;clearTimeout(searchTimer)}});
document.addEventListener('compositionend',e=>{if(e.target.id==='search'){searchComposing=false;clearTimeout(searchTimer);applySearch(e.target)}});
document.addEventListener('input',e=>{if(e.target.id!=='search'||e.isComposing||searchComposing)return;clearTimeout(searchTimer);const input=e.target;searchTimer=setTimeout(()=>{if(input.isConnected)applySearch(input)},180)});
function syncNavigationAccessibility(){const aside=document.querySelector('.sidebar');if(!aside)return;const mobile=window.matchMedia('(max-width:700px)').matches,open=aside.classList.contains('open');aside.inert=mobile&&!open;const trigger=document.querySelector('[data-action="menu"]');if(trigger)trigger.setAttribute('aria-expanded',String(open));if(!mobile){aside.classList.remove('open');document.querySelector('.overlay')?.classList.remove('open')}}
function setMobileMenu(open){document.querySelector('.sidebar')?.classList.toggle('open',open);document.querySelector('.overlay')?.classList.toggle('open',open);syncNavigationAccessibility();if(open)document.querySelector('.nav button.active')?.focus();else document.querySelector('[data-action="menu"]')?.focus()}
window.addEventListener('resize',syncNavigationAccessibility);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.sidebar.open'))setMobileMenu(false)});
document.addEventListener('change',e=>{if(e.target.id!=='show-new-password')return;for(const name of ['newPassword','confirmPassword']){const input=document.querySelector(`[name="${name}"]`);if(input)input.type=e.target.checked?'text':'password'}});
function memberStatusSummary(){const active=db.members.filter(m=>m.active);return `<div class="member-status-summary">${[['','全部成员',db.members.length,'users'],['空闲','当前空闲',active.filter(m=>memberStatus(m)==='空闲').length,'check'],['忙碌','正在忙碌',active.filter(m=>memberStatus(m)==='忙碌').length,'chip'],['请假','请假中',active.filter(m=>memberStatus(m)==='请假').length,'calendar']].map(([value,label,count,ico])=>`<button class="member-status-tile ${filter===value?'selected':''}" data-action="member-quick-filter" data-value="${value}" aria-pressed="${filter===value}"><span class="stat-icon ${value==='空闲'?'green':value==='请假'?'orange':''}">${icon(ico)}</span><span><small>${label}</small><b>${count}<i>人</i></b></span>${icon('chevron')}</button>`).join('')}</div>`}
